name: Deploy Static Math Site

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Required for clean gh-pages push
          fetch-depth: 0             # Fetch full history

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./            # Root folder contains index.html, assets/
          publish_branch: gh-pages   # Deploys to gh-pages branch
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          force_orphan: true         # Creates a fresh branch to avoid git errors
          keep_files: false          # Clears previous deploy files
